### ISSUE TITLE
已经收藏的小程序如何判断

### ISSUE THREAD

**Issue by funtask** [guren-cloud/weplug-add-tips#1]
本地缓存到期后应该还是会显示的吧

**Comment by safe-dog** [comment]
本地缓存，除非用户删除了小程序（会同时删除缓存等信息） 否则一般是不会存在“过期”的行为的~
目前好像还没有接口能判断出用户是否收藏了小程序，所以抱歉这个功能无法实现的。只能先预想个大概，用户点击提示，点击知道，下次不提示~
